language: php

php:
  - 7.0
  - 7.1

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - sudo apt-get update
  - travis_retry composer self-update

install:
  - sudo apt-get install -y ffmpeg libavcodec-extra-53
  - travis_retry composer update --prefer-source $PREFER_LOWEST
  - travis_retry composer require php-ffmpeg/php-ffmpeg
  - travis_retry composer require league/flysystem-aws-s3-v3
  - printf "\n" | pecl install imagick
  - sudo apt-get install -y ghostscript

script:
  - phpunit

branches:
  only:
    - master
    - laravel55
