language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source $PREFER_LOWEST 
  - printf "\n" | pecl install imagick

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

branches:
  only:
    - master
    - stable
