language: php

php:
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.0
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_install:
  - sudo apt-get update
  - travis_retry composer self-update

install:
  - sudo apt-get install -y ffmpeg libavcodec-extra-53
  - travis_retry composer update --prefer-source $PREFER_LOWEST
  - travis_retry composer require php-ffmpeg/php-ffmpeg
  - printf "\n" | pecl install imagick

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

branches:
  only:
    - master
    - stable
